// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: helloworld.proto

package helloworld

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/thanos-io/OpenConfig/golang"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Lang int32

const (
	Lang_UNKNOWN Lang = 0
	Lang_ENGLISH Lang = 1
	Lang_POLISH  Lang = 2
	Lang_GERMAN  Lang = 3
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENGLISH",
		2: "POLISH",
		3: "GERMAN",
	}
	Lang_value = map[string]int32{
		"UNKNOWN": 0,
		"ENGLISH": 1,
		"POLISH":  2,
		"GERMAN":  3,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_proto_enumTypes[0].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_helloworld_proto_enumTypes[0]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

type HelloWorldApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to XCommand:
	//	*HelloWorldApp_Hello
	//	*HelloWorldApp_Bye
	XCommand isHelloWorldApp_XCommand `protobuf_oneof:"_command"`
}

func (x *HelloWorldApp) Reset() {
	*x = HelloWorldApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldApp) ProtoMessage() {}

func (x *HelloWorldApp) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldApp.ProtoReflect.Descriptor instead.
func (*HelloWorldApp) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

func (m *HelloWorldApp) GetXCommand() isHelloWorldApp_XCommand {
	if m != nil {
		return m.XCommand
	}
	return nil
}

func (x *HelloWorldApp) GetHello() *HelloCommand {
	if x, ok := x.GetXCommand().(*HelloWorldApp_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *HelloWorldApp) GetBye() *ByeCommand {
	if x, ok := x.GetXCommand().(*HelloWorldApp_Bye); ok {
		return x.Bye
	}
	return nil
}

type isHelloWorldApp_XCommand interface {
	isHelloWorldApp_XCommand()
}

type HelloWorldApp_Hello struct {
	Hello *HelloCommand `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HelloWorldApp_Bye struct {
	Bye *ByeCommand `protobuf:"bytes,2,opt,name=bye,proto3,oneof"`
}

func (*HelloWorldApp_Hello) isHelloWorldApp_XCommand() {}

func (*HelloWorldApp_Bye) isHelloWorldApp_XCommand() {}

type HelloCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Year      int64  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	World     string `protobuf:"bytes,3,opt,name=world,proto3" json:"world,omitempty"`
	Lang      Lang   `protobuf:"varint,4,opt,name=lang,proto3,enum=helloworld.Lang" json:"lang,omitempty"`
	AddReally bool   `protobuf:"varint,5,opt,name=add_really,json=addReally,proto3" json:"add_really,omitempty"`
}

func (x *HelloCommand) Reset() {
	*x = HelloCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloCommand) ProtoMessage() {}

func (x *HelloCommand) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloCommand.ProtoReflect.Descriptor instead.
func (*HelloCommand) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloCommand) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *HelloCommand) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *HelloCommand) GetLang() Lang {
	if x != nil {
		return x.Lang
	}
	return Lang_UNKNOWN
}

func (x *HelloCommand) GetAddReally() bool {
	if x != nil {
		return x.AddReally
	}
	return false
}

type ByeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang Lang `protobuf:"varint,1,opt,name=lang,proto3,enum=helloworld.Lang" json:"lang,omitempty"`
	// Types that are assignable to XCommand:
	//	*ByeCommand_World
	//	*ByeCommand_Just
	XCommand isByeCommand_XCommand `protobuf_oneof:"_command"`
}

func (x *ByeCommand) Reset() {
	*x = ByeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeCommand) ProtoMessage() {}

func (x *ByeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeCommand.ProtoReflect.Descriptor instead.
func (*ByeCommand) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *ByeCommand) GetLang() Lang {
	if x != nil {
		return x.Lang
	}
	return Lang_UNKNOWN
}

func (m *ByeCommand) GetXCommand() isByeCommand_XCommand {
	if m != nil {
		return m.XCommand
	}
	return nil
}

func (x *ByeCommand) GetWorld() *ByeWorldCommand {
	if x, ok := x.GetXCommand().(*ByeCommand_World); ok {
		return x.World
	}
	return nil
}

func (x *ByeCommand) GetJust() *ByeJustCommand {
	if x, ok := x.GetXCommand().(*ByeCommand_Just); ok {
		return x.Just
	}
	return nil
}

type isByeCommand_XCommand interface {
	isByeCommand_XCommand()
}

type ByeCommand_World struct {
	World *ByeWorldCommand `protobuf:"bytes,2,opt,name=world,proto3,oneof"`
}

type ByeCommand_Just struct {
	Just *ByeJustCommand `protobuf:"bytes,3,opt,name=just,proto3,oneof"`
}

func (*ByeCommand_World) isByeCommand_XCommand() {}

func (*ByeCommand_Just) isByeCommand_XCommand() {}

type ByeWorldCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ByeWorldCommand) Reset() {
	*x = ByeWorldCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByeWorldCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeWorldCommand) ProtoMessage() {}

func (x *ByeWorldCommand) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeWorldCommand.ProtoReflect.Descriptor instead.
func (*ByeWorldCommand) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{3}
}

type ByeJustCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ByeJustCommand) Reset() {
	*x = ByeJustCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByeJustCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeJustCommand) ProtoMessage() {}

func (x *ByeJustCommand) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeJustCommand.ProtoReflect.Descriptor instead.
func (*ByeJustCommand) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{4}
}

var File_helloworld_proto protoreflect.FileDescriptor

var file_helloworld_proto_rawDesc = []byte{
	0x0a, 0x10, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x10,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x79, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x41, 0x70,
	0x70, 0x12, 0x30, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x2a, 0x0a, 0x03, 0x62, 0x79, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x42, 0x79,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x03, 0x62, 0x79, 0x65, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x0c,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x61,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x64, 0x64, 0x52, 0x65, 0x61, 0x6c, 0x6c, 0x79, 0x22,
	0xa5, 0x01, 0x0a, 0x0a, 0x42, 0x79, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x42, 0x79, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x48, 0x00, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x6a, 0x75, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x42, 0x79, 0x65, 0x4a, 0x75, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x75, 0x73, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x79, 0x65, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x42, 0x79,
	0x65, 0x4a, 0x75, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2a, 0x3e, 0x0a, 0x04,
	0x4c, 0x61, 0x6e, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x50, 0x4f, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x45,
	0x52, 0x4d, 0x41, 0x4e, 0x10, 0x03, 0x1a, 0x04, 0xc0, 0xb8, 0x02, 0x00, 0x42, 0x6e, 0x0a, 0x21,
	0x69, 0x6f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x68, 0x61, 0x6e, 0x6f, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_proto_rawDescData = file_helloworld_proto_rawDesc
)

func file_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_proto_rawDescData)
	})
	return file_helloworld_proto_rawDescData
}

var file_helloworld_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_helloworld_proto_goTypes = []interface{}{
	(Lang)(0),               // 0: helloworld.Lang
	(*HelloWorldApp)(nil),   // 1: helloworld.HelloWorldApp
	(*HelloCommand)(nil),    // 2: helloworld.HelloCommand
	(*ByeCommand)(nil),      // 3: helloworld.ByeCommand
	(*ByeWorldCommand)(nil), // 4: helloworld.ByeWorldCommand
	(*ByeJustCommand)(nil),  // 5: helloworld.ByeJustCommand
}
var file_helloworld_proto_depIdxs = []int32{
	2, // 0: helloworld.HelloWorldApp.hello:type_name -> helloworld.HelloCommand
	3, // 1: helloworld.HelloWorldApp.bye:type_name -> helloworld.ByeCommand
	0, // 2: helloworld.HelloCommand.lang:type_name -> helloworld.Lang
	0, // 3: helloworld.ByeCommand.lang:type_name -> helloworld.Lang
	4, // 4: helloworld.ByeCommand.world:type_name -> helloworld.ByeWorldCommand
	5, // 5: helloworld.ByeCommand.just:type_name -> helloworld.ByeJustCommand
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_helloworld_proto_init() }
func file_helloworld_proto_init() {
	if File_helloworld_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByeWorldCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByeJustCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_helloworld_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HelloWorldApp_Hello)(nil),
		(*HelloWorldApp_Bye)(nil),
	}
	file_helloworld_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ByeCommand_World)(nil),
		(*ByeCommand_Just)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_proto_depIdxs,
		EnumInfos:         file_helloworld_proto_enumTypes,
		MessageInfos:      file_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_proto = out.File
	file_helloworld_proto_rawDesc = nil
	file_helloworld_proto_goTypes = nil
	file_helloworld_proto_depIdxs = nil
}
